### ISSUE TITLE
Bluetooth Error: undefined

### ISSUE THREAD

**Issue by Nkawu** [beeb/coffee-scale-app#32]
I started getting this error today with my scale. Using the Bluefy app on iOS 17.1.1 in order to use Web BLE on my iPhone. Has been working flawlessly for a long time. Any ideas?

![IMG_3467](https://github.com/beeb/coffee-scale-app/assets/1527620/bebfd736-72ad-4324-8569-b7fd5699842a)

**Comment by beeb** [comment]
Not sure, I have never used Bluefy or iOS to be fair. I usually use Google Chrome on Android. I started rewriting the firmware in Rust so maybe that will fix it?

**Comment by Nkawu** [comment]
I just checked again and it's working now! I suspect a recent Bluefy update must have broken (and now fixed) the connection.
