### ISSUE TITLE
Max transmit weight? Scale shows 992 gram, web view shows -318grams.

### ISSUE THREAD

**Issue by graphefruit** [beeb/coffee-scale-app#40]
Hey there @beeb,
very very cool project!
A user of [Beanconqueror](https://github.com/graphefruit/Beanconqueror), which is a coffee brew companion, reached out to me, if I want to integrate this DIY scale here and he sent me a sample scale - Pretty awesome!

I'm using the python-firmware with the scale.

After 3 hours of testing how to handle the data in Javascript (Cordova Base) I've come across that the weight above 350grams or so, can't be converted rightly.

I've tested with an object, which is 992 grams in total, which is displayed by the scale lcd, but the transmitted weight (also in the test version here: https://coffee.beeb.li/) is then displayed as -318.32g.

I know that the python scale is the old firmware, but I'd be happy to discuss here, if there is a chance to get like to 2kg, to make it for pour over possible.

Thank you so much! :) 
Have a great cup of coffee
Lars

**Comment by beeb** [comment]
Hey! Thanks for your message, that's awesome! I'm currently developing the next version of the firmware which will use a larger type for the weight value and it will lift the current limit. Stay tuned!

**Comment by graphefruit** [comment]
Hey @beeb,
that was a fast feedback! Awesome.
I hope the question is ok for you:
Will the new firmware stick to the actual code solution?
```
const value = (newFirmware ? dataView?.getInt32(0, false) : dataView?.getInt16(0, false)) ?? 0
currentWeight.set(value / 100.0)
``` 
After I can't test the RUST-FIrmware, but I made it work to patch on cordova also to the Dataview, it would be awesome so I don't need to update the app afterwards.

Thank you again!
Realy like the project!
Lars

**Comment by beeb** [comment]
I'm not sure I understand the question, but the new rust firmware will use 32 bits for the weight value, so the web-app will not change. It's already supporting both versions of the firmware.

**Comment by graphefruit** [comment]
> I'm not sure I understand the question, but the new rust firmware will use 32 bits for the weight value, so the web-app will not change. It's already supporting both versions of the firmware.

Yeah, sorry I try to clarify:
I use the python firmware.
The code which is used here is `dataView?.getInt16(0, false)`
You mentioned above, that you are on a new firmware, which will then send the new weight correctly (not -318, then 992).
Will the `.getInt16` then also get changed to a `.getInt32`? 

Edit:
Or will the python firmware will get no update anymore, just the rust firmware?

**Comment by beeb** [comment]
I have no plan to update the micropython firmware yeah.. But it would be an easy change if you decide to fork it. Tomorrow I can send more details if you really don't want to use the new rust firmware in the future

**Comment by graphefruit** [comment]
> I have no plan to update the micropython firmware yeah.. But it would be an easy change if you decide to fork it. Tomorrow I can send more details if you really don't want to use the new rust firmware in the future

Got it! Thanks.
I thought it would be good to support both kind of firmwares.
I just found this weired situation while I was playing with espresso/filter situation.

I asked the user which sent me the scale to maybe just switch to RUST and drop python support completely so.

**Comment by beeb** [comment]
I just released the new firmware officially, feel free to check it out! I will mark this as closed since the problem doesn't happen with the new firmware.
