### ISSUE TITLE
Giant scale freezes when zoom out and zoom back

### ISSUE THREAD

**Issue by mazzdriver** [beeb/coffee-scale-app#44]
When changing scale from regular 100% to smaller (90% and less), picture will change the scale, layout will change.  After turning scale back ("Reset scale" or zoom exactly at 100%) layout will change again, but picture won't changed.

![image](https://github.com/beeb/coffee-scale-app/assets/82169861/f2f3f723-4336-4d8f-bf7e-3ec37644e081)

**Comment by beeb** [comment]
Hey! sorry i completely missed your issue somehow. This looks like the chart it not re-rendering when the resolution changes. Let me see if I can fix it

**Comment by beeb** [comment]
Should be fixed by #55 let me know if you still have issues!
