### ISSUE TITLE
Prusa Repository

### ISSUE THREAD

**Issue by nhadler** [beeb/coffee-scale-app#5]
Hi,

I was having issues downloading your stl's for this project. Is there any way to get them posted here or on another service?

Thank you!
Nicholas

**Comment by beeb** [comment]
Looks like prusaprinters indeed is having issues at the moment. I upload the STLs [on Dropbox](https://www.dropbox.com/sh/y72eei7ldssmts3/AAB3qLmbaYeQ_2kDVDoz3PT7a?dl=0) in the mean time.

Hopefully they fix it soon as there was useful information in the print description.

**Comment by beeb** [comment]
Seems the website is [up again](https://www.prusaprinters.org/prints/36112-diy-bluetooth-coffeeespresso-scale). Closing
